name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dashboard code
        uses: actions/checkout@v3
        with:
          repository: Dreamacro/clash-dashboard
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "17.x"
          cache: pnpm
      - name: Install package and build
        run: |
          pnpm install
          pnpm build
      - name: Build IPK
        run: |
          mkdir -p control
          PKG_NAME="clash-dashboard"
          TAG_NAME=$(date +%Y%m%d%H%M)

          cat <<EOF >control/control
          Package: ${PKG_NAME}
          Version: 1.0-${TAG_NAME}
          SourceName: ${PKG_NAME}
          Architecture: x86_64
          Description:  ${PKG_NAME}
          EOF

          pushd control
          tar cvzf ../control.tar.gz ./*
          popd

          mkdir -p data/www
          cp -r dist data/www/clash

          pushd data
          tar cvzf ../data.tar.gz ./*
          popd

          echo 2.0 >debian-binary
          tar cvzf ${PKG_NAME}_1.0-${TAG_NAME}.ipk ./control.tar.gz ./data.tar.gz ./debian-binary
          rm -rf control control.tar.gz data.tar.gz data debian-binary
          mkdir -p output
          mv ${PKG_NAME}_1.0-${TAG_NAME}.ipk output
          echo "NEED_PUB=1" >> $GITHUB_ENV
      - if: ${{ env.NEED_PUB == '1' }}
        name: Release and upload assets
        uses: softprops/action-gh-release@v0.1.6
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
